name: inventory
description: An app to locally manage your items at hand
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite:
  flutter_screenutil: ^5.8.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - assets/logo.jpg

  fonts:
    - family: Karla
      fonts:
        - asset: assets/Karla/Karla-Bold.ttf
          weight: 700
        - asset: assets/Karla/Karla-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/Karla/Karla-ExtraBold.ttf
          weight: 700
        - asset: assets/Karla/Karla-ExtraBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/Karla/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/Karla/Karla-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/Karla/Karla-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/Karla/Karla-Italic.ttf
          style: italic
        - asset: assets/Karla/Karla-Light.ttf
          weight: 300
        - asset: assets/Karla/Karla-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/Karla/Karla-Medium.ttf
          weight: 400
        - asset: assets/Karla/Karla-MediumItalic.ttf
          style: italic
          weight: 400
        - asset: assets/Karla/Karla-Regular.ttf
        - asset: assets/Karla/Karla-SemiBold.ttf
          weight: 700
        - asset: assets/Karla/Karla-SemiBoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/Karla/Karla-VariableFont_wght.ttf
    
